### ISSUE TITLE
Moodle 4.5: modal view doesn't work

### ISSUE THREAD

**Issue by mattgig** [SN-RECIT-formation-a-distance/moodle-filter_recitautolink#11]
When you embed a page with the modal view parameter, e.g. [[p/My Page]] the modal doesn't open in Moodle 4.5 and you get an error in the browser console.

```
Uncaught TypeError: $ is not a function
    at new recit.filter.autolink.Popup (filter.js:9:1041)
    at recit.filter.autolink.popupIframe (filter.js:12:130)
    at <anonymous>:1:23
```

My guess is that the jQuery library is not properly loaded due to some changes in Moodle 4.5.

**Comment by gustavobazzo** [comment]
Hello @mattgig,

Thank you for your comment.
We are currently migrating our plugins to Moodle 4.5.
We should release the new version in a few months.

Kind regards!

**Comment by mattgig** [comment]
Adjusting the code in filter.js should fix the issue:

```
        document.body.appendChild(this.modal);

        this.modal.style.display = 'block';

        this.modal.classList.add('show');



        let that = this;

        document.addEventListener('click', function(event) {

            if (event.target.classList.contains('modal-backdrop')) {

                that.hide();

            }

        });



        this.modal.addEventListener('hidden.bs.modal', () => that.destroy());

    }

    destroy() {

        this.modal.remove();

    }

    update() {

        // handleUpdate logic if needed

    }

    hide() {

        this.modal.style.display = 'none';

        this.modal.classList.remove('show');

    }
```
    
Disclaimer: I used the Mistral AI to fix that part of the code.
